name: âœ… PR checks

on: pull_request

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:

    - name: â¤µï¸ Checkout code
      uses: actions/checkout@v4

    - name: âš™ï¸ Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: ğŸ§ª Run unit tests
      run: mvn test

    - name: ğŸ” Sonar code analysis
      run: sonarsource/sonarcloud-github-action@2.3.0
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    - name: ğŸ”† Quality Gate
      uses: sonarsource/sonarqube-quality-gate-action@1.1.0
      timeout-minutes: 2
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
